import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub, AiFillMail } from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
// import design from '../pages/design.png';
// import code from '../pages/code.png';
// import consulting from '../pages/consulting.png';
import html from '../public/html.png';
import css from '../public/css.png';
import javascript from '../public/javascript.png';
import react from '../public/react.png';
import redux from '../public/redux.png';
import nextjs from '../public/nextjs.png';
import nodejs from '../public/nodejs.png';
import expressjs from '../public/expressjs.png';
import mongodb from '../public/mongodb.png';
import bootstrap from '../public/bootstrap.png';
import tailwind from '../public/tailwind.png';

import { useState } from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl font-pacifico text-cyan-600'>Pratap Karmakar</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={()=>{setDarkMode(!darkMode)}} className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <p className='text-5xl py-2 text-gray-500 font-medium inline pr-2 md:text-6xl'>Hi! I'm,</p><p className='text-5xl py-2 text-teal-600 font-medium inline md:text-6xl'>Pratap Karmakar</p>
            <h3 className='text-4xl text-teal-500 py-6 md:text-5xl'>A Web Developer</h3>
            <p className='text-2xl  py-5 leading-8 text-gray-600 md:text-xl mx-w-lg mx-auto'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta repudiandae quo aut! Aspernatur nulla nemo reprehenderit accusamus soluta sint ullam enim. Veniam excepturi amet ullam architecto cum delectus voluptas laborum!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin />
            <AiFillGithub />
            <AiFillMail />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 '>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>
        </section> 



        <section>
          <div inner className='p-20 shadow-md rounded-md'>
            <h3 header className='text-center  p-10 text-5xl text-teal-700 font-medium relative'>My Skills</h3>
            <div className='flex flex-wrap gap-12 justify-center items-center my-6 max-w-lg mx-auto'>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={html} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>HTML</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={css} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>CSS</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={javascript} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>JavaScript</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={react} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>React</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={redux} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>Redux</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={nextjs} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold '>NextJs</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={bootstrap} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>Bootstrap</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={tailwind} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>Tailwind</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={nodejs} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>NodeJs</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={expressjs} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>ExpressJs</h3>
              </div>
              <div className='flex flex-col items-center'>
                <div className='relative w-14 h-14'>
                  <Image src={mongodb} />
                </div>
                <h3 className='pt-1 text-lg text-gray-600 font-bold'>MongoDB</h3>
              </div>
            </div>
          </div>
        </section>




        <section>
          <div>
            <h1 className='text-center  p-20 text-5xl text-teal-700 font-medium'>My Projects</h1>
          </div>
        </section>

      </main>
    </div>
  )
}



